### ISSUE TITLE
oc logs -f dc/letsenc error

### ISSUE THREAD

**Issue by badjano** [caruccio/letsencrypt#1]
Error from server (NotFound): deploymentconfigs "letsenc" not found

Then I tried:
**oc logs -f dc/ssl**
and got:

creating main config file /getssl/getssl.cfg
Making domain directory - /getssl/xxxxxxx.xxx
creating domain config file in /getssl/xxxxxxx.xxx/getssl.cfg
xxxxxxx.xxx: DNS lookup failed for xxxxxxx.xxx
getssl: xxxxxxx.xxx: exiting due to config errors

( xxxxxxx.xxx being my domain )

**Comment by badjano** [comment]
Sorry, I forgot to add INCLUDE_WWW=false because I was trying to create one for a subdomain, but after I fixed and and ran: 
oc logs -f dc/ssl
the certificate keys were empty:

creating main config file /getssl/getssl.cfg
Making domain directory - /getssl/xxx.xxx.xxx
creating domain config file in /getssl/xxx.xxx.xxx/getssl.cfg
creating account key /getssl/account.key
creating key - /getssl/account.key
Generating RSA private key, 4096 bit long modulus
................................++
.....................................................................................++
e is 65537 (0x10001)
creating key - /getssl/xxx.xxx.xxx/xxx.xxx.xxx.key
Generating RSA private key, 4096 bit long modulus
...........................................................................................................................................++
......................................................................................++
e is 65537 (0x10001)
creating domain csr - /getssl/xxx.xxx.xxx/xxx.xxx.xxx.csr
Registering account
getssl: Error registering account ...  "Error creating new registration 


And when I do "oc get pods" the status of the container is set to CrashLoopBackOff

**Comment by caruccio** [comment]
Hey. Did you updated your DNS server to point to your openshift app?

**Comment by caruccio** [comment]
BTW, this code is outdated. I believe letsenc has deativated protocol v1 in favor of v2.
I strongly suggest you to use https://github.com/Neilpang/acme.sh
